config/routes.rb
CheerioBook::Application.routes.draw do

  devise_for :users, controllers: {omniauth_callbacks: "omniauth_callbacks"}

  resources :children do
    resources :rewards
    resources :chores
  end
  
  match 'children/:children_id/chores/:id/complete' => 'chores#complete', :as => :complete_chore
  match 'children/:children_id/chores/:id/delete' => 'chores#delete', :as => :delete_chore
  
  
  match 'children/:children_id/rewards/:id/rewarded' => 'rewards#complete', :as => :complete_reward
  match 'children/:children_id/rewards/:id/delete' => 'rewards#delete', :as => :delete_reward
  
  
  root to: 'children#index'
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  

end

app/controllers/children_controller.rb
class ChildrenController < ApplicationController
  
  before_filter :authenticate_user!
  
  # GET /children
  # GET /children.json
  def index
    @children = Child.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @children }
    end
  end

  # GET /children/1
  # GET /children/1.json
  def show
    @child = Child.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @child }
    end
  end

  # GET /children/new
  # GET /children/new.json
  def new
    @child = Child.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @child }
    end
  end

  # GET /children/1/edit
  def edit
    @child = Child.find(params[:id])
  end

  # POST /children
  # POST /children.json
  def create
    @child = Child.new(params[:child])

    respond_to do |format|
      if @child.save
        format.html { redirect_to @child, notice: 'Child was successfully created.' }
        format.json { render json: @child, status: :created, location: @child }
      else
        format.html { render action: "new" }
        format.json { render json: @child.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /children/1
  # PUT /children/1.json
  def update
    @child = Child.find(params[:id])

    respond_to do |format|
      if @child.update_attributes(params[:child])
        format.html { redirect_to @child, notice: 'Child was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @child.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /children/1
  # DELETE /children/1.json
  def destroy
    @child = Child.find(params[:id])
    @child.destroy

    respond_to do |format|
      format.html { redirect_to children_url }
      format.json { head :no_content }
    end
  end
 
end

app/helpers/children_helper.rb
module ChildrenHelper
end

app/views/children/_form.html.erb
<%= form_for(@child) do |f| %>
  <% if @child.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@child.errors.count, "error") %> stopped this working:</h2>
      <ul>
      	<% @child.errors.full_messages.each do |msg| %>
	        <li><%= msg %></li>
	      <% end %>
      </ul>
    </div>
  <% end %>

   
  <div>
	  <%= f.label :name, 'Image:' %>
    <%= f.text_field :name, placeholder: 'name...', autofocus: true %>
  </div>

  <div>
    <%= f.label :image, 'Image:' %>
    <%= f.file_field :image %>
  </div>
  
  <div>
    <%= f.label :dob, 'Date of Birth:' %>
    <%= f.date_select :dob %>
  </div>
 
    <%= f.submit 'Submit' %>

<% end %>

app/views/children/edit.html.erb
<h1>Editing child</h1>

<%= render 'form' %>

<%= link_to 'Show', @child %> |
<%= link_to 'Back', children_path %>

app/views/children/index.html.erb
<div class="hero-unit">
	<h3>Children</h3>

	
<% @children.each do |child| %>
 <div class="well">
	  <%= image_tag (child.image_url(:thumb)), class: "feature" %>
    <%= link_to child.name, child_path(child) %>
    <%= child.dob %>
    <span class="admin">
    <%= link_to (image_tag 'edit_16.png'), edit_child_path(child) %>
    <%= link_to (image_tag'1354409256_delete.png'), child, method: :delete, data: { confirm: 'Are you sure?' } %>
    </span>
   <span id="child_bank">Current bank: <%= child.bank %></span>
   <%= child.total %>
 </div>  
<% end %>

	<div class="well"><%= link_to 'Add Child', new_child_path %></div>


</div>

app/views/children/new.html.erb
<div class="hero-unit">
<h3>Add child</h3>

<%= render 'form' %>

<%= link_to 'Back', children_path %>
</div>

app/views/children/show.html.erb
<div class="hero-unit">
	
	<%= link_to "back", children_path %>
  
	<div class="well">
	 	  <%= image_tag @child.image_url(:thumb), class: "feature" %>
		  <span id="child_name"><%= @child.name %></span>
	    aged: <%= @child.dob %> |
	    <%= link_to (image_tag 'edit_16.png'), edit_child_path(@child) %> 
	    <span id="child_bank"><b>Bank:</b> <%= @child.bank %> Pts</span>  
	</div>

	<p id="notice"><%= notice %></p>
	<div class="row">
	  <div class="span4">
			<div class="hero-unit">
			  <h4>Chores</h4>
				<ul class="incomplete">
					<% @child.chores.incomplete.each do |chore| %>          
					  <li><%= chore.name %>, <%= chore.points %>pts, <%= chore.due_date.strftime("due: %A") %> - <span class="admin"><%= link_to "Done", complete_chore_path(@child.id, chore.id) %><%= link_to (image_tag'1354409256_delete.png'), delete_chore_path(@child.id, chore.id) %></span></li>
			  	<% end %>
				</ul>
		
				<ul class="completed">
					<% @child.chores.completed.each do |chore| %>
					<li><%= chore.name %><%= link_to (image_tag'1354409256_delete.png'), delete_chore_path(@child.id, chore.id) %></li>
					<% end %>
				</ul>

				<%= form_for [@child, @child.chores.new] do |f| %>
				  <%= f.text_field :name, placeholder: 'describe chore...' %> 
					<%= f.number_field :points, placeholder: 'points...' %> 
					<%= f.text_field :due_date, placeholder: 'due date...' %>
				  <%= f.submit %>
				<% end %>
	
			</div> <!-- end of hero-unit -->
	</div>

	<div class="row">
	<div class="span4">
		<div class="hero-unit">
			<h4>Rewards</h4>
			<ul class="incomplete">
				<% @child.rewards.incomplete.each do |reward| %>        
				<li><%= image_tag reward.image_url(:tiny) %><%= reward.name %>, <%= reward.costs %>pts, 
					<span class="admin">- <%= button_to "Done", complete_reward_path(@child.id, reward.id) %><%= link_to (image_tag'1354409256_delete.png'), delete_reward_path(@child.id, reward.id) %><span></li>
				<% end %>
			</ul>

			<ul class="completed">
				<% @child.rewards.completed.each do |reward| %>
				  <li><%= reward.name %><%= link_to (image_tag'1354409256_delete.png'), delete_reward_path(@child.id, reward.id) %></li>
				<% end %>
			</ul>

			<%= form_for [@child, @child.rewards.new] do |f| %>
			  <%= f.text_field :name, placeholder: 'describe reward...' %> 
				<%= f.number_field :costs, placeholder: 'points...' %> 
				<%= f.file_field :image %>
			  <%= f.submit %>
			<% end %>

		</div>
</div>