config/routes.rb
CheerioBook::Application.routes.draw do

  devise_for :users, controllers: {omniauth_callbacks: "omniauth_callbacks"}

  resources :children do
    resources :rewards
    resources :chores
  end
  
  match 'children/:children_id/chores/:id/complete' => 'chores#complete', :as => :complete_chore
  match 'children/:children_id/chores/:id/delete' => 'chores#delete', :as => :delete_chore
  
  
  match 'children/:children_id/rewards/:id/rewarded' => 'rewards#complete', :as => :complete_reward
  match 'children/:children_id/rewards/:id/delete' => 'rewards#delete', :as => :delete_reward
  
  
  root to: 'children#index'
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  

end

app/models/reward.rb
class Reward < ActiveRecord::Base
  attr_accessible :child_id, :costs, :image, :name, :rewarded
  
  validates :costs, presence: true
  validates :name, presence: true
  
  belongs_to :child
  
  mount_uploader :image, ImageUploader
  
  scope :completed, where(:rewarded => true)
  scope :incomplete, where(:rewarded => false)
  
  after_save :update_bank
  
  def update_bank
    # this will call calculate_bank on before save
    child.save
  end
end

app/controllers/rewards_controller.rb
class RewardsController < ApplicationController
  
  attr_accessor :rewarded
  before_filter :authenticate_user!
  
  # GET /rewards
  # GET /rewards.json
  def index
    @rewards = Reward.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @rewards }
    end
  end

  # GET /rewards/1
  # GET /rewards/1.json
  def show
    @reward = Reward.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @reward }
    end
  end

  # GET /rewards/new
  # GET /rewards/new.json
  def new
    @reward = Reward.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @reward }
    end
  end

  # GET /rewards/1/edit
  def edit
    @reward = Reward.find(params[:id])
  end

  # POST /rewards
  # POST /rewards.json
  def create
     @child = Child.find(params[:child_id])
     @reward = @child.rewards.new(params[:reward])

     respond_to do |format|
       if @reward.save
         format.html { redirect_to child_url(@child), notice: 'Reward was successfully created.' }
         #figure out the json l8ter
       else
         format.html { redirect_to child_url(@child) }
         #figure out the json l8ter
       end
     end
   end

  # PUT /rewards/1
  # PUT /rewards/1.json
  def update
    @reward = Reward.find(params[:id])

    respond_to do |format|
      if @reward.update_attributes(params[:reward])
        format.html { redirect_to @reward, notice: 'Reward was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @reward.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rewards/1
  # DELETE /rewards/1.json
  def destroy
    @reward = Reward.find(params[:id])
    @reward.destroy

    respond_to do |format|
      format.html { redirect_to child_url(@child) }
      format.json { head :no_content }
    end
  end
  
  def delete
    @child = Child.find(params[:children_id])
    @reward = @child.rewards.find(params[:id])
    @reward.destroy
    redirect_to child_url(@child)
  end
  
  def complete
    @child = Child.find(params[:children_id])
    @reward = @child.rewards.find(params[:id])
    @reward.rewarded = true
    @reward.save
    redirect_to child_url(@child)
  end
end

app/helpers/rewards_helper.rb
module RewardsHelper
end

app/views/rewards/_form.html.erb
<%= form_for(@reward) do |f| %>
  <% if @reward.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@reward.errors.count, "error") %> prohibited this reward from being saved:</h2>

      <ul>
      <% @reward.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :image %><br />
    <%= f.text_field :image %>
  </div>
  <div class="field">
    <%= f.label :rewarded %><br />
    <%= f.check_box :rewarded %>
  </div>
  <div class="field">
    <%= f.label :costs %><br />
    <%= f.number_field :costs %>
  </div>
  <div class="field">
    <%= f.label :child_id %><br />
    <%= f.number_field :child_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/rewards/edit.html.erb
<h1>Editing reward</h1>

<%= render 'form' %>

<%= link_to 'Show', @reward %> |
<%= link_to 'Back', rewards_path %>

app/views/rewards/index.html.erb
<h1>Listing rewards</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Image</th>
    <th>Rewarded</th>
    <th>Costs</th>
    <th>Child</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @rewards.each do |reward| %>
  <tr>
    <td><%= reward.name %></td>
    <td><%= reward.image %></td>
    <td><%= reward.rewarded %></td>
    <td><%= reward.costs %></td>
    <td><%= reward.child_id %></td>
    <td><%= link_to 'Show', reward %></td>
    <td><%= link_to 'Edit', edit_reward_path(reward) %></td>
    <td><%= link_to 'Destroy', reward, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Reward', new_reward_path %>

app/views/rewards/new.html.erb
<h1>New reward</h1>

<%= render 'form' %>

<%= link_to 'Back', rewards_path %>

app/views/rewards/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @reward.name %>
</p>

<p>
  <b>Image:</b>
  <%= @reward.image %>
</p>

<p>
  <b>Rewarded:</b>
  <%= @reward.rewarded %>
</p>

<p>
  <b>Costs:</b>
  <%= @reward.costs %>
</p>

<p>
  <b>Child:</b>
  <%= @reward.child_id %>
</p>


<%= link_to 'Edit', edit_reward_path(@reward) %> |
<%= link_to 'Back', rewards_path %>