config/routes.rb
CheerioBook::Application.routes.draw do

  devise_for :users, controllers: {omniauth_callbacks: "omniauth_callbacks"}

  resources :children do
    resources :rewards
    resources :chores
  end
  
  match 'children/:children_id/chores/:id/complete' => 'chores#complete', :as => :complete_chore
  match 'children/:children_id/chores/:id/delete' => 'chores#delete', :as => :delete_chore
  
  
  match 'children/:children_id/rewards/:id/rewarded' => 'rewards#complete', :as => :complete_reward
  match 'children/:children_id/rewards/:id/delete' => 'rewards#delete', :as => :delete_reward
  
  
  root to: 'children#index'
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  

end

app/models/chore.rb
class Chore < ActiveRecord::Base
  attr_accessible :child_id, :completed, :due_date, :name, :points
  

  # sort out flash message for validations
  validates :name, presence: true
  validates :points, presence: true
  validates :due_date, presence: true


  belongs_to :child
  scope :completed, where(:completed => true)
  scope :incomplete, where(:completed => false)
  
  after_save :update_bank

  def update_bank
    # this will call calculate_bank on before save
    child.save
  end  
end



  

app/controllers/chores_controller.rb
class ChoresController < ApplicationController
  
  attr_accessor :completed
  before_filter :authenticate_user!
  
  # GET /chores
  # GET /chores.json
  def index
    @chores = Chore.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @chores }
    end
  end

  # GET /chores/1
  # GET /chores/1.json
  def show
    @chore = Chore.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @chore }
    end
  end

  # GET /chores/new
  # GET /chores/new.json
  def new
    @chore = Chore.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @chore }
    end
  end

  # GET /chores/1/edit
  def edit
    @chore = Chore.find(params[:id])
  end

  # POST /chores
  # POST /chores.json
  def create
    @child = Child.find(params[:child_id])
    @chore = @child.chores.new(params[:chore])

    respond_to do |format|
      if @chore.save
        format.html { redirect_to child_url(@child), notice: 'Chore was successfully created.' }
        #figure out the json l8ter
      else
        format.html { redirect_to child_url(@child) }
        #figure out the json l8ter
      end
    end
  end

  # PUT /chores/1
  # PUT /chores/1.json
  def update
    @chore = Chore.find(params[:id])

    respond_to do |format|
      if @chore.update_attributes(params[:chore])
        format.html { redirect_to @chore, notice: 'Chore was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @chore.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /chores/1
  # DELETE /chores/1.json
  def destroy
    @chore = Chore.find(params[:id])
    @chore.destroy

    respond_to do |format|
      format.html { redirect_to chores_url }
      format.json { head :no_content }
    end
  end
  
  def complete
    @child = Child.find(params[:children_id])
    @chore = @child.chores.find(params[:id])
    @chore.completed = true
    @chore.save
    redirect_to child_url(@child)
  end
  
  
  def delete
    @child = Child.find(params[:children_id])
    @chore = @child.chores.find(params[:id])
    @chore.destroy
    redirect_to child_url(@child)
  end
  
  
end 


  
  
  
 
  

app/helpers/chores_helper.rb
module ChoresHelper
end

app/views/chores/_form.html.erb
<%= form_for(@chore) do |f| %>
  <% if @chore.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@chore.errors.count, "error") %> prohibited this chore from being saved:</h2>

      <ul>
      <% @chore.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :points %><br />
    <%= f.number_field :points %>
  </div>
  
  <div class="field">
    <%= f.label :due_date %><br />
    <%= f.date_select :due_date %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/chores/edit.html.erb
<h1>Editing chore</h1>

<%= render 'form' %>

<%= link_to 'Show', @chore %> |
<%= link_to 'Back', chores_path %>

app/views/chores/index.html.erb
<h1>Listing chores</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Points</th>
    <th>Completed</th>
    <th>Child</th>
    <th>Due date</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @chores.each do |chore| %>
  <tr>
    <td><%= chore.name %></td>
    <td><%= chore.points %></td>
    <td><%= chore.completed %></td>
    <td><%= chore.child_id %></td>
    <td><%= chore.due_date %></td>
    <td><%= link_to 'Show', chore %></td>
    <td><%= link_to 'Edit', edit_chore_path(chore) %></td>
    <td><%= link_to 'Destroy', chore, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Chore', new_chore_path %>

app/views/chores/new.html.erb
<h1>New chore</h1>

<%= render 'form' %>

<%= link_to 'Back', chores_path %>

app/views/chores/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @chore.name %>
</p>

<p>
  <b>Points:</b>
  <%= @chore.points %>
</p>

<p>
  <b>Completed:</b>
  <%= @chore.completed %>
</p>

<p>
  <b>Child:</b>
  <%= @chore.child_id %>
</p>

<p>
  <b>Due date:</b>
  <%= @chore.due_date %>
</p>
<%= link_to 'Edit', edit_chore_path(@chore) %> |
<%= link_to 'Back', chores_path %>